name = "naptw-worker-cronjob"
main = "src/index.ts"
compatibility_date = "2023-12-06"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "shorturl"
database_id = "ae594a40-0220-4123-bf95-77079b0a6943"

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["0 0 1 * *"] # run every month