name: Cronjob Auto Deploy

on:
  push:
    branches:
      - main
    paths:
      - cronjob/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cronjob
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: cronjob/yarn.lock
      
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: ./cronjob
          command: deploy